/**
 * Frame-sequence manifest. Regenerated by scripts/extract-frames.mjs —
 * edit that script, not this file.
 */
export const FRAME_COUNT = 451;
export const FRAME_DIR = '/frames';
export const FRAME_EXT = 'webp';
export const HOLD_FRAME = 56;
export const framePath = (i) =>
  `${FRAME_DIR}/hero_${String(i + 1).padStart(4, '0')}.${FRAME_EXT}`;
