#!/usr/bin/env node
/**
 * Turn the hero clip into a scrubbable WebP frame sequence.
 *
 *   node scripts/extract-frames.mjs media-src/hero.mp4
 *
 * ~15fps, max 1600px wide, WebP. Setting currentTime on a <video> to scrub
 * stutters and behaves differently in every browser; drawing a preloaded
 * image to a canvas does not.
 *
 * ffmpeg on this machine has no libwebp encoder, so ffmpeg lays down PNGs
 * and sharp does the WebP pass.
 */
import { execFileSync } from 'node:child_process';
import {
  mkdtempSync, rmSync, mkdirSync, readdirSync, writeFileSync, copyFileSync, statSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import sharp from 'sharp';

const SRC = process.argv[2] || 'media-src/hero.mp4';
const OUT = 'public/frames';
const FPS = Number(process.env.FPS || 15);
const WIDTH = Number(process.env.WIDTH || 1600);
const QUALITY = Number(process.env.QUALITY || 72);
const CONCURRENCY = 8;

const tmp = mkdtempSync(path.join(tmpdir(), 'noctis-frames-'));

try {
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
  mkdirSync('public/media', { recursive: true });

  console.log(`decoding ${SRC} at ${FPS}fps…`);
  execFileSync(
    'ffmpeg',
    [
      '-hide_banner', '-loglevel', 'error', '-y',
      '-i', SRC,
      '-vf', `fps=${FPS},scale='min(${WIDTH},iw)':-2:flags=lanczos`,
      path.join(tmp, 'f_%04d.png'),
    ],
    { stdio: 'inherit' }
  );

  const pngs = readdirSync(tmp).filter((f) => f.endsWith('.png')).sort();
  if (!pngs.length) throw new Error('ffmpeg produced no frames');

  console.log(`encoding ${pngs.length} frames to webp q${QUALITY}…`);
  let done = 0;
  let cursor = 0;

  const worker = async () => {
    while (cursor < pngs.length) {
      const i = cursor++;
      const out = path.join(OUT, `hero_${String(i + 1).padStart(4, '0')}.webp`);
      await sharp(path.join(tmp, pngs[i]))
        .webp({ quality: QUALITY, effort: 5, smartSubsample: true })
        .toFile(out);
      if (++done % 50 === 0) process.stdout.write(`  ${done}/${pngs.length}\n`);
    }
  };
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));

  const count = pngs.length;
  // A frame from the far side of the orbit: the car is lit, not silhouetted.
  const hold = Math.floor((count * 30) / 100);
  copyFileSync(
    path.join(OUT, `hero_${String(hold + 1).padStart(4, '0')}.webp`),
    'public/media/hero-poster.webp'
  );

  writeFileSync(
    'src/modules/frames.js',
    `/**
 * Frame-sequence manifest. Regenerated by scripts/extract-frames.mjs —
 * edit that script, not this file.
 */
export const FRAME_COUNT = ${count};
export const FRAME_DIR = '/frames';
export const FRAME_EXT = 'webp';
export const HOLD_FRAME = ${hold};
export const framePath = (i) =>
  \`\${FRAME_DIR}/hero_\${String(i + 1).padStart(4, '0')}.\${FRAME_EXT}\`;
`
  );

  const bytes = readdirSync(OUT).reduce(
    (n, f) => n + statSync(path.join(OUT, f)).size,
    0
  );
  console.log(`\nframes:  ${count} @ ${FPS}fps, max ${WIDTH}px, q${QUALITY}`);
  console.log(`weight:  ${(bytes / 1048576).toFixed(1)} MB total`);
  console.log(`poster:  public/media/hero-poster.webp (frame ${hold})`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
