#!/usr/bin/env bash
# Turn the hero clip into a scrubbable WebP frame sequence.
#
#   ./scripts/extract-frames.sh media-src/hero.mp4
#
# ~15fps, max 1600px wide, WebP. Setting currentTime on a <video> to scrub
# stutters and behaves differently in every browser; drawing a preloaded
# image to a canvas does not.
set -euo pipefail

SRC="${1:-media-src/hero.mp4}"
OUT="public/frames"
FPS="${FPS:-15}"
WIDTH="${WIDTH:-1600}"
QUALITY="${QUALITY:-70}"

[ -f "$SRC" ] || { echo "missing source: $SRC" >&2; exit 1; }

rm -rf "$OUT"
mkdir -p "$OUT"

ffmpeg -hide_banner -loglevel error -y -i "$SRC" \
  -vf "fps=${FPS},scale='min(${WIDTH},iw)':-2:flags=lanczos" \
  -c:v libwebp -quality "$QUALITY" -compression_level 6 -preset picture -an \
  "$OUT/hero_%04d.webp"

COUNT=$(find "$OUT" -name 'hero_*.webp' | wc -l | tr -d ' ')
[ "$COUNT" -gt 0 ] || { echo "no frames written" >&2; exit 1; }

# A frame from the far side of the orbit: the car is lit, not silhouetted.
HOLD=$(( COUNT * 30 / 100 ))
POSTER=$(printf "%s/hero_%04d.webp" "$OUT" "$(( HOLD + 1 ))")
mkdir -p public/media
cp "$POSTER" public/media/hero-poster.webp

cat > src/modules/frames.js <<EOF
/**
 * Frame-sequence manifest. Regenerated by scripts/extract-frames.sh —
 * edit that script, not this file.
 */
export const FRAME_COUNT = ${COUNT};
export const FRAME_DIR = '/frames';
export const FRAME_EXT = 'webp';
export const HOLD_FRAME = ${HOLD};
export const framePath = (i) =>
  \`\${FRAME_DIR}/hero_\${String(i + 1).padStart(4, '0')}.\${FRAME_EXT}\`;
EOF

echo "frames:  ${COUNT} @ ${FPS}fps, max ${WIDTH}px, q${QUALITY}"
echo "weight:  $(du -sh "$OUT" | cut -f1)"
echo "poster:  public/media/hero-poster.webp (frame ${HOLD})"
